Description of mctSimulateBvecs
Home > compute > mctSimulateBvecs.m
mctSimulateBvecs
PURPOSE
SYNOPSIS
function bvecs = mctSimulateBvecs(nbvecs)
DESCRIPTION
function bvecs = mctSimulateBvecs(nbvecs)
 the reis no analysitc way to precompute bvecs.
 so here we load precomputed bvecs provided with camino and saved in:
 /vistasoft/trunk/mrDiffusion/data/gradFiles/caminoPts
 These bvecs are generated by simulating electrostatic repulsion.
 Example:
 s_mct_simulated
 See also, test_mictrotrack_simulated_signal_recover
 (C) 2011 Stanford VISTA team.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mctBuildDwiFromFg
mctSimulateFG
mctSimulateFG2
SOURCE CODE
function bvecs = mctSimulateBvecs(nbvecs)
%
%function bvecs = mctSimulateBvecs(nbvecs)
%
% the reis no analysitc way to precompute bvecs.
% so here we load precomputed bvecs provided with camino and saved in:
% /vistasoft/trunk/mrDiffusion/data/gradFiles/caminoPts
%
% These bvecs are generated by simulating electrostatic repulsion.
%
% Example:
%
% s_mct_simulated
%
% See also, test_mictrotrack_simulated_signal_recover
%
% (C) 2011 Stanford VISTA team.
pts_dir     = fullfile(fileparts(mrvRootPath),'mrDiffusion/data/gradFiles/caminoPts');
directions = dlmread(fullfile(pts_dir, sprintf('Elec%03d.txt', nbvecs)));
% The first line should be equal to nbvecs:
assert(directions(1) == nbvecs, 'There is something wrong with the camino points file');
% The format is: n,x1,y1,z1,x2,y2,z2 ... xn,yn,zn
bvecs = [directions(2:3:end), ...
         directions(3:3:end), ...
         directions(4:3:end)];
return