Description of feGet
Home > fe > feGet.m
feGet
PURPOSE
Get function for fascicle evaluation structure
SYNOPSIS
function val = feGet(fe,param,varargin)
DESCRIPTION
 Get function for fascicle evaluation structure
   val = feGet(fe,param,varargin)
 INPUTS:
  Coords    - Nx3 set of coordinates in image space
  voxelIndices - Vector of 1's and 0's, there is a one for each
              location the the connectome coordinates for which there is
              a match in the coords
 Franco & Brian (c) Stanford Vista Team 2012
---------- List of arguments ----
 Name of the current fe structure.
 name = feGet(fe,'name')
----------
 The type of objes (always, fascicle evaluation)
 type = feGet(fe,'type')
----------
 Structure of parameters and results from LIFE analysis
 life = feGet(fe,'life')
----------
 Return the connectome (fiber group) in image coordinates.
 fg = feGEt(fe,'fg img')
----------
 return the connectome in acpc coordinates.
 fg  = feGet(fg,'fg acpc')
----------
 Return the VOI comprised by the full connectome.
 roi = feGet(fe,'roi')
----------
 Transforms between coords for fg, roi, and dwi data
 xform = feGet(fe,'xform')
----------
 Load the diffusion weighted data.
 dwi = feGet(fe,'dwi')
----------
 Return the path to the diffusion weighted data file.
 dwiFile = feGet(fe,'dwifile')
----------
 Load the repeated-measure diffusion weighted data.
 dwi = feGet(fe,'dwirepeat')
----------
 Load the repeated measure of the diffusion weighted data.
 dwiFile = feGet(fe,'dwirepeatfile')
----------
 Directory where the LiFe structes are saved by defualt.
 sdir = feGet(fe,'savedir');
----------
 Diffusion directions.
 val = feGet(fe,'bvecs');
----------
 Indices to the diffusion directions in the DWi 4th Dimension.
 val = feGet(fe,'bvecs indices');
----------
 Number of B0's
 val = feGet(fe,'n bvals');
----------
 B0 Values.
 bval = feGet(fe,'bvals')
----------
 Returns a nVoxels X nBvecs array of measured diffusion signal
 val = feGet(fe,'dsiinvox');
 val = feGet(fe,'dsiinvox',voxelsIndices);
 val = feGet(fe,'dsiinvox',coords);
----------
 Returns a nVoxels X nBvecs array of demeaned diffusion signal
 val =feGet(fe,'dsiinvoxdemeaned');
 val =feGet(fe,'dsiinvoxdemeaned',voxelsIndices);
 val =feGet(fe,'dsiinvoxdemeaned',coords);
----------
 Get the diffusion signal at 0 diffusion weighting (B0) for this voxel
 val = feGet(fe,'b0signalvoxel');
 val = feGet(fe,'b0signalvoxel',voxelIndex);
 val = feGet(fe,'b0signalvoxel',coords);
----------
 Return a subset of fibers from the conenctome.
 fg = feGet(fe,'fiberssubset',fiberList);
----------
 Return the coordinates of the VOI comprised in the connectome.
 Always in image space.
 coords = feGet(fe,'roi coords')
----------
 Number of voxels in the connectome/VOI.
 nVoxels = feGet(fe,'n voxels')
----------
 Indexes of actually used voxels.
 These can be different than the number of voxels in the VOI in case some
 voxels have no fibers in them.
 TO BE DEPRECATED.
 indxUsedVx = feGet(fe,'index of used voxels')
----------
 Number of actually used voxels.
 This can be less than the number of voxels in the VOI in case some
 voxels have no fibers in them.
 TO BE DEPRECATED.
 nUsedVx = feGet(fe,'index of used voxels')
----------
 Returns the first index to a voxel in the dSig vector.
 The dSig vector is 1:nBvecs*nVoxels.
 val = feGet(fe,'start rows')
----------
 Return the rows corresponding to a set of voxels.
 rows = feGet(fe,'voxel rows',idxVoxel)
----------
 Return the model (M matrix), or a subset of it.
 Mfiber = feGet(fe,'M fiber');
 Mfiber = feGet(fe,'model',voxelsIndices);
 Mfiber = feGet(fe,'model',coords);
----------
 Return a subset of measurements from the fiber portion of M matrix
 The rows of M are specified.  Remember that the rows refer to a
 combination of voxel and measurement direction and potentially in the
 future a b-value.  Hence, the rows are not specific to a voxel.
 Mfiber = feGet(fe,'mfiber subset',rowsToKeep);
----------
 Pairing of fibers and nodes in each voxel.
 v2fnp = feGet(fe,'v2fnp');
----------
 Tensors computed for each node and fiber in a set of voxels.
 t = feGet(fe,'tensors')
 t = feGet(fe,'tensors',voxelsIndices);
 t = feGet(fe,'tensors',coords);
----------
 Get all the tensors in a single voxel.
 val = feGet(fe,'voxtensors',voxelIndex)
 val = feGet(fe,'voxtensors',coord)
----------
 Returns the model (M) with only a subset of columns (fibers).
 fiberList is a vector of indexes, e.g, [1 10 100]
 M = feGet(fe,'keepfibers',fiberList)
----------
 Isotropic portion of M matrix. Returns the matrix for the full model or
 for a subset of voxels.
 Miso = feGet(fe,'M iso')
 Miso = feGet(fe,'M iso',voxelsIndices)
 Miso = feGet(fe,'M iso',coords)
----------
 Total number of nodes in each voxel The voxel2FN pairs are row size
 equals number of nodes and column size is always 2. The entries of
 the first column are the fiber number. The entries in the second
 column are the node of the fiber inside the voxel.
 val = feGet(fe,'n nodes');
 val = feGet(fe,'n nodes',voxelsIndices);
 val = feGet(fe,'n nodes',coords);
----------
 Return the total number of fibers for all the voxels or in a set of
 voxels.
 nFibers = feGet(fe,'uniquefnum');           % all the voxels
 nFibers = feGet(fe,'uniquefnum',[1 2 3 4]); % for some the voxels,
                                             % specified by indexes
 nFibers = feGet(fe,'uniquefnum',coords);    % for some the voxels,
                                             % specified by coordinates
----------
 Return the indexes of the fibers for all the voxels or in a set of
 voxels.
 idxFibers = feGet(fe,'uniquef');           % all the voxels
 idxFibers = feGet(fe,'uniquef',[1 2 3 4]); % for some the voxels,
                                            % specified by indexes
 idxFibers = feGet(fe,'uniquef',coords);    % for some the voxels,
                                            % specified by coordinates
----------
 Return the total number of fibers for all the voxels or in a set of
 voxels
 nFibers = feGet(fe,'totfnum');           % all the voxels
 nFibers = feGet(fe,'totfnum',[1 2 3 4]); % for some the voxels,
                                          % specified by indexes
 nFibers = feGet(fe,'totfnum',coords);    % for some the voxels,
                                          % specified by coordinates
----------
 Return the indexes of the fibers for all the voxels or in a set of
 voxels
 idxFibers = feGet(fe,'totf');             % all the voxels
 idxFibers = feGet(fe,'totf',[1 2 3 4]);   % for some the voxels,
                                           % specified by indexes
 idxFibers = feGet(fe,'totfibers',coords); % for some the voxels,
                                           % specified by coordinates
----------
 Return the number of fibers in the model.
 nFibers = feGet(fe,'n fibers');
----------
 Weights of the isotropic voxel signals, this is the mean signal in
 each voxel.
 val = feGet(fe,'iso weights');
 val = feGet(fe,'iso weights'coords)
 val = feGet(fe,'iso weights',voxelIndices)
----------
 Weights of the fiber component. For all the fibers or a subset of
 them.
 w = feGet(fe,'fiber weights')
 w = feGet(fe,'fiber weights',fiberIndices)
----------
 Weights of the fiber component with a subset of the fibers' weights
 set to zero. This can be used to test the loss in RMSE for the
 connectome when a subset of fibers is removed, but the connectome is
 not fitted again.
 w = feGet(fe,'fiber weights test',fiberIndices)
----------
 Predicted signal (demeaned) with a subset of fibers' weights set to 0.
 This can be used to test the loss in RMSE for the connectome when a
 subset of fibers is removed, but the connectome is not fitted again.
 pSig = feGet(fe,'pSig fiber test',fiberIndices);
 pSig = feGet(fe,'pSig fiber test',fiberIndices,voxelIndices);
 pSig = feGet(fe,'pSig fiber test',fiberIndices,coords);
----------
 Measured signal in VOI, this is the raw signal. not demeaned
 dSig = feGet(fe,'dSig full')
---------
 Measured signal in VOI, demeaned, this is the signal used for the
 fiber-portion of the M model.
 dSig = feGet(fe,'dsigdemeaned');
 dSig = feGet(fe,'dsigdemeaned',[1 10 100]);
 dSig = feGet(fe,'dsigdemeaned',coords);
---------
 Get the demeaned signal for a subset of rows.
 Useful for cross-validation.
 dSig = feGet(fe,'dsigrowssubset',voxelsList);
---------
 Predicted signal of fiber alone (demeaned).
 pSig = feGet(fe,'pSig fiber');
 pSig = feGet(fe,'pSig fiber',coords);
 pSig = feGet(fe,'pSig fiber',voxelIndices);
---------
 Predicted measured signal from both fiber and iso
 pSig = feGet(fe,'pSig full')
 pSig = feGet(fe,'pSig full',coords)
 pSig = feGet(fe,'pSig full',voxelIndices)
---------
 The woxels returned by a fit of LiFE by voxel/fiber
 w = feGet(fe,'fiberweightsvoxelwise')
---------
 Predict the diffusion signal for the fiber component
 with the voxel-wise fit of LiFE
 pSig = feGet(fe,'psigfvoxelwise')
 pSig = feGet(fe,'psigfvoxelwise',coords)
 pSig = feGet(fe,'psigfvoxelwise',voxelIndices)
---------
 Predict the diffusion signal for the fiber component
 with the voxel-wise fit of LiFE, return the an array of pSigXnVoxel
 pSig = feGet(fe,'psigfvoxelwisebyvoxel')
 pSig = feGet(fe,'psigfvoxelwisebyvoxel',coords)
 pSig = feGet(fe,'psigfvoxelwisebyvoxel',voxelIndices)
---------
 The fiber and isotropic weights as a long vector
 w = feGet(fe,'fullweights')
---------
 Return the global R2 (fraction of variance explained) of the full life
 model.
 R2 = feGet(fe,'total r2');
---------
 Percent variance explained
 R2 = feGet(fe,'explained variance')
---------
 Root mean squared error of the LiFE fit to the whole data
 rmse = feGet(fe,'rmse')
---------
 Residual signal: (fiber prediction - measured_demeaned).
 res = feGet(fe,'res sig fiber')
---------
 Residual signal: (full model prediction - measured signal).
 res = feGet(fe,'res sig full');
---------
 Residual signal: (fiber model prediction - demeaned measured signal)
 with added mean signal. Res is returned as a vector.
 This is used to reconstruct an image (volume) to be used for the
 refinement process.
 res = feGet(fe,'fiber res sig with mean');
 res = feGet(fe,'fiber res sig with mean',coords);
 res = feGet(fe,'fiber res sig with mean',voxelIndices);
---------
 Residual signal fiber model prediction - demeaned measured signal
 with added mean signal. Res is returned as an array (nBvecs x nVoxel).
 This is used to reconstruct an image (volume) to be used for the
 refinement process.
 res = feGet(fe,'fiber res sig with mean voxel');
 res = feGet(fe,'fiber res sig with mean voxel',coords);
 res = feGet(fe,'fiber res sig with mean voxel',voxelIndices);
---------
 Predicted signal by the fiber model in a set of voxels.
 Vox subfield stores per voxel within the VOI. The pSig has size of the
 dwi. - It is stored as val = pSig(X,Y,Z,Theta)
 pSig = feGet(fe, 'pSig fiber by voxel');
 pSig = feGet(fe, 'pSig fiber by voxel',coords);
 pSig = feGet(fe, 'pSig fiber by voxel',voxelIndex);
---------
 Return a column vector of the proportion of variance explained in
 each voxel.
 R2byVox = feGet(fe,'voxr2');
 R2byVox = feGet(fe,'voxr2',coords);
---------
 Return a column vector of the proportion of variance explained in
 each voxel. (Normalized to the squared mean diffusion signal in each voxel)
 R2byVox = feGet(fe,'voxr2zero');
 R2byVox = feGet(fe,'voxr2zero',coords);
---------
 Return the percent of varince explained in each voxel.
 R2byVox = feGet(fe,'var exp by voxel');
 R2byVox = feGet(fe,'var exp by voxel',coords);
---------
 Demeaned diffusion signal in each voxel.
 dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel');
 dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',coords);
 dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',vxIndex);
---------
 Full (measured) signal in each voxel.
 dSigByVoxel = feGet(fe,'dSig full by Voxel');
 dSigByVoxel = feGet(fe,'dSig full by Voxel',coords);
 dSigByVoxel = feGet(fe,'dSig full by Voxel',vxIndex);
---------
 Predicted signal by the full model in a set of voxeles.
 pSigByVoxel = feGet(fe, 'pSig full by voxel');
 pSigByVoxel = feGet(fe, 'pSig full by voxel',coords);
 pSigByVoxel = feGet(fe, 'pSig full by voxel',voxelIndex);
---------
 A volume of RMSE values.
 RMSE = feGet(fe,'vox rmse')
 RMSE = feGet(fe,'vox rmse',coords)
 RMSE = feGet(fe,'vox rmse',vxIndex)
---------
 A volume of RMSE values with a subset of fibers' weights set to 0.
 RMSE = feGet(fe,'vox rmse',fiberIndices)
 RMSE = feGet(fe,'vox rmse',fiberIndices,coords)
 RMSE = feGet(fe,'vox rmse',fiberIndices,voxelIndex)
---------
 Fibers' residual signal by voxel.
 res = feGet(fe,'res sig fiber vox')
 res = feGet(fe,'res sig fiber vox',coords)
 res = feGet(fe,'res sig fiber vox',vxIndex)
---------
 Full (measured) residual signal by voxel.
 res = feGet(fe,'res sig full vox')
 res = feGet(fe,'res sig full vox',coords)
 res = feGet(fe,'res sig full vox',vxIndex)
---------
 Fibers' residual signal by voxel with mean signal added (with added
 isotropic component).
 This is used to compute the residual signal for the refinement.
 res = feGet(fe,'fiber res sig with mean vox')
 res = feGet(fe,'fiber res sig with mean vox',coords)
 res = feGet(fe,'fiber res sig with mean vox',vxIndex)
---------
 Residual signal full model prediction from a multi-voxel fit.
 res = feGet(fe,'res sig full voxfit');
 res = feGet(fe, 'res sig full voxfit',coords);
 res = feGet(fe, 'res sig full voxfit',voxelIndex);
---------
 Fiber density statistics.
 Computes the fiber density (how many fibers in each voxel)
 We compute the following values:
 (1) The number of fibers in each voxel
 (2) The number of unique fibers with non-zero weights
 (3) The sum of the weights in each voxel
 (4) The mean of the weights in each voxel
 (5) The variance of the weigths in each voxel
 pSig = feGet(fe,'fiberdensity');
---------
 Given an VOI or a set of indices to voxels returns the indices of the matching voxels inside the big
 volume, which ordinarily represents the full connectome.
 voxelIndices = feGet(fe,'voxelsindices',coords)
                IMPORTANT: Size(coords) must be Nx3;
 voxelIndices = feGet(fe,'voxelsindices',voxelIndices)
                IMPORTANT: Indices MUST be a column vector for this
                code to work. Size(voxelIndices) = Nx1;
---------
 Given an VOI finds the indices of the matching voxels inside the big
 volume, which ordinarily represents the full connectome.
 foundVoxels = feGet(fe,'find voxels',coords)
 coords is a Nx3 set of coordinates in image space
 foundVoxels is a vector of 1's and 0's, there is a one for each
 location the the connectome coordinates for which there is a match in
 the coords
---------
 Given a set of VOI coords finds the row numbers of the Model matrix
 (or equivalently the dSig vector) that represent the data for this
 set of VOI coords.
 foundVoxels = feGet(fe,'coords 2 rows',coords)
 coords      - a Nx3 set of coordinates in image space
 foundVoxels - a binary vector that is 1 for each Model matrix row
               that corresponds to at least one of the coords.
---------
 Quaternian transformation from IMAGE space to ACPC space.
 xform = feGet(fe,'xform')
---------
 Quaternian transformation from ACPC space to IMAGE space.
 xform = feGet(fe,'xform')
---------
 Dimensions of the DW volume.
 dim = feGet(fe,'dims')
---------
 Dimensions of the maps of parameters and results.
 dims = feGet(fe, 'mapsize')
---------
 Path to the 3D Anatomy Volume.
 anatomyfile = feGet(fe, 't1 file')
 End of feGet.m parameters,
 Franco Pestilli (c) Stanford Vista Team 2012
CROSS-REFERENCE INFORMATION
This function calls:
feGet Get function for fascicle evaluation structure
feGetRep Get function for fascicle evaluation structure, to use for a repeated
This function is called by:
feConnectomeBuildModel Compute matrix to predict directional diffusion in each voxel from fibers
feConnectomeInit
feConnectomeReduceFibers Deletes a set of fibers from the signal and the M matrix.
feConnectomeReduceVoxels Select the voxels to keep (extract) in a connectome matrix
feConnectomeSelectFibers Deletes a set of fibers from the signal and the M matrix.
feConnectomeSetDwi
feGet Get function for fascicle evaluation structure
feGetRep Get function for fascicle evaluation structure, to use for a repeated
feSet Set fascicle evaluation parameters
SOURCE CODE
function val = feGet(fe,param,varargin)
% Get function for fascicle evaluation structure
%
%   val = feGet(fe,param,varargin)
%
%
% INPUTS:
%  Coords    - Nx3 set of coordinates in image space
%  voxelIndices - Vector of 1's and 0's, there is a one for each
%              location the the connectome coordinates for which there is
%              a match in the coords
%
%
% Franco & Brian (c) Stanford Vista Team 2012
%
%
%---------- List of arguments ----
% Name of the current fe structure.
% name = feGet(fe,'name')
%----------
% The type of objes (always, fascicle evaluation)
% type = feGet(fe,'type')
%----------
% Structure of parameters and results from LIFE analysis
% life = feGet(fe,'life')
%----------
% Return the connectome (fiber group) in image coordinates.
% fg = feGEt(fe,'fg img')
%----------
% return the connectome in acpc coordinates.
% fg  = feGet(fg,'fg acpc')
%----------
% Return the VOI comprised by the full connectome.
% roi = feGet(fe,'roi')
%----------
% Transforms between coords for fg, roi, and dwi data
% xform = feGet(fe,'xform')
%----------
% Load the diffusion weighted data.
% dwi = feGet(fe,'dwi')
%----------
% Return the path to the diffusion weighted data file.
% dwiFile = feGet(fe,'dwifile')
%----------
% Load the repeated-measure diffusion weighted data.
% dwi = feGet(fe,'dwirepeat')
%----------
% Load the repeated measure of the diffusion weighted data.
% dwiFile = feGet(fe,'dwirepeatfile')
%----------
% Directory where the LiFe structes are saved by defualt.
% sdir = feGet(fe,'savedir');
%----------
% Diffusion directions.
% val = feGet(fe,'bvecs');
%----------
% Indices to the diffusion directions in the DWi 4th Dimension.
% val = feGet(fe,'bvecs indices');
%----------
% Number of B0's
% val = feGet(fe,'n bvals');
%----------
% B0 Values.
% bval = feGet(fe,'bvals')
%----------
% Returns a nVoxels X nBvecs array of measured diffusion signal
% val = feGet(fe,'dsiinvox');
% val = feGet(fe,'dsiinvox',voxelsIndices);
% val = feGet(fe,'dsiinvox',coords);
%----------
% Returns a nVoxels X nBvecs array of demeaned diffusion signal
% val =feGet(fe,'dsiinvoxdemeaned');
% val =feGet(fe,'dsiinvoxdemeaned',voxelsIndices);
% val =feGet(fe,'dsiinvoxdemeaned',coords);
%----------
% Get the diffusion signal at 0 diffusion weighting (B0) for this voxel
% val = feGet(fe,'b0signalvoxel');
% val = feGet(fe,'b0signalvoxel',voxelIndex);
% val = feGet(fe,'b0signalvoxel',coords);
%----------
% Return a subset of fibers from the conenctome.
% fg = feGet(fe,'fiberssubset',fiberList);
%----------
% Return the coordinates of the VOI comprised in the connectome.
% Always in image space.
% coords = feGet(fe,'roi coords')
%----------
% Number of voxels in the connectome/VOI.
% nVoxels = feGet(fe,'n voxels')
%----------
% Indexes of actually used voxels.
% These can be different than the number of voxels in the VOI in case some
% voxels have no fibers in them.
%
% TO BE DEPRECATED.
% indxUsedVx = feGet(fe,'index of used voxels')
%----------
% Number of actually used voxels.
% This can be less than the number of voxels in the VOI in case some
% voxels have no fibers in them.
%
% TO BE DEPRECATED.
% nUsedVx = feGet(fe,'index of used voxels')
%----------
% Returns the first index to a voxel in the dSig vector.
% The dSig vector is 1:nBvecs*nVoxels.
% val = feGet(fe,'start rows')
%----------
% Return the rows corresponding to a set of voxels.
% rows = feGet(fe,'voxel rows',idxVoxel)
%----------
% Return the model (M matrix), or a subset of it.
% Mfiber = feGet(fe,'M fiber');
% Mfiber = feGet(fe,'model',voxelsIndices);
% Mfiber = feGet(fe,'model',coords);
%----------
% Return a subset of measurements from the fiber portion of M matrix
% The rows of M are specified.  Remember that the rows refer to a
% combination of voxel and measurement direction and potentially in the
% future a b-value.  Hence, the rows are not specific to a voxel.
% Mfiber = feGet(fe,'mfiber subset',rowsToKeep);
%----------
% Pairing of fibers and nodes in each voxel.
% v2fnp = feGet(fe,'v2fnp');
%----------
% Tensors computed for each node and fiber in a set of voxels.
% t = feGet(fe,'tensors')
% t = feGet(fe,'tensors',voxelsIndices);
% t = feGet(fe,'tensors',coords);
%----------
% Get all the tensors in a single voxel.
% val = feGet(fe,'voxtensors',voxelIndex)
% val = feGet(fe,'voxtensors',coord)
%----------
% Returns the model (M) with only a subset of columns (fibers).
% fiberList is a vector of indexes, e.g, [1 10 100]
% M = feGet(fe,'keepfibers',fiberList)
%----------
% Isotropic portion of M matrix. Returns the matrix for the full model or
% for a subset of voxels.
% Miso = feGet(fe,'M iso')
% Miso = feGet(fe,'M iso',voxelsIndices)
% Miso = feGet(fe,'M iso',coords)
%----------
% Total number of nodes in each voxel The voxel2FN pairs are row size
% equals number of nodes and column size is always 2. The entries of
% the first column are the fiber number. The entries in the second
% column are the node of the fiber inside the voxel.
% val = feGet(fe,'n nodes');
% val = feGet(fe,'n nodes',voxelsIndices);
% val = feGet(fe,'n nodes',coords);
%----------
% Return the total number of fibers for all the voxels or in a set of
% voxels.
% nFibers = feGet(fe,'uniquefnum');           % all the voxels
% nFibers = feGet(fe,'uniquefnum',[1 2 3 4]); % for some the voxels,
%                                             % specified by indexes
% nFibers = feGet(fe,'uniquefnum',coords);    % for some the voxels,
%                                             % specified by coordinates
%----------
% Return the indexes of the fibers for all the voxels or in a set of
% voxels.
% idxFibers = feGet(fe,'uniquef');           % all the voxels
% idxFibers = feGet(fe,'uniquef',[1 2 3 4]); % for some the voxels,
%                                            % specified by indexes
% idxFibers = feGet(fe,'uniquef',coords);    % for some the voxels,
%                                            % specified by coordinates
%----------
% Return the total number of fibers for all the voxels or in a set of
% voxels
% nFibers = feGet(fe,'totfnum');           % all the voxels
% nFibers = feGet(fe,'totfnum',[1 2 3 4]); % for some the voxels,
%                                          % specified by indexes
% nFibers = feGet(fe,'totfnum',coords);    % for some the voxels,
%                                          % specified by coordinates
%----------
% Return the indexes of the fibers for all the voxels or in a set of
% voxels
% idxFibers = feGet(fe,'totf');             % all the voxels
% idxFibers = feGet(fe,'totf',[1 2 3 4]);   % for some the voxels,
%                                           % specified by indexes
% idxFibers = feGet(fe,'totfibers',coords); % for some the voxels,
%                                           % specified by coordinates
%----------
% Return the number of fibers in the model.
% nFibers = feGet(fe,'n fibers');
%----------
% Weights of the isotropic voxel signals, this is the mean signal in
% each voxel.
% val = feGet(fe,'iso weights');
% val = feGet(fe,'iso weights'coords)
% val = feGet(fe,'iso weights',voxelIndices)
%----------
% Weights of the fiber component. For all the fibers or a subset of
% them.
% w = feGet(fe,'fiber weights')
% w = feGet(fe,'fiber weights',fiberIndices)
%----------
% Weights of the fiber component with a subset of the fibers' weights
% set to zero. This can be used to test the loss in RMSE for the
% connectome when a subset of fibers is removed, but the connectome is
% not fitted again.
% w = feGet(fe,'fiber weights test',fiberIndices)
%----------
% Predicted signal (demeaned) with a subset of fibers' weights set to 0.
% This can be used to test the loss in RMSE for the connectome when a
% subset of fibers is removed, but the connectome is not fitted again.
%
% pSig = feGet(fe,'pSig fiber test',fiberIndices);
% pSig = feGet(fe,'pSig fiber test',fiberIndices,voxelIndices);
% pSig = feGet(fe,'pSig fiber test',fiberIndices,coords);
%----------
% Measured signal in VOI, this is the raw signal. not demeaned
%
% dSig = feGet(fe,'dSig full')
%---------
% Measured signal in VOI, demeaned, this is the signal used for the
% fiber-portion of the M model.
%
% dSig = feGet(fe,'dsigdemeaned');
% dSig = feGet(fe,'dsigdemeaned',[1 10 100]);
% dSig = feGet(fe,'dsigdemeaned',coords);
%---------
% Get the demeaned signal for a subset of rows.
% Useful for cross-validation.
% dSig = feGet(fe,'dsigrowssubset',voxelsList);
%---------
% Predicted signal of fiber alone (demeaned).
% pSig = feGet(fe,'pSig fiber');
% pSig = feGet(fe,'pSig fiber',coords);
% pSig = feGet(fe,'pSig fiber',voxelIndices);
%---------
% Predicted measured signal from both fiber and iso
% pSig = feGet(fe,'pSig full')
% pSig = feGet(fe,'pSig full',coords)
% pSig = feGet(fe,'pSig full',voxelIndices)
%---------
% The woxels returned by a fit of LiFE by voxel/fiber
% w = feGet(fe,'fiberweightsvoxelwise')
%---------
% Predict the diffusion signal for the fiber component
% with the voxel-wise fit of LiFE
% pSig = feGet(fe,'psigfvoxelwise')
% pSig = feGet(fe,'psigfvoxelwise',coords)
% pSig = feGet(fe,'psigfvoxelwise',voxelIndices)
%---------
% Predict the diffusion signal for the fiber component
% with the voxel-wise fit of LiFE, return the an array of pSigXnVoxel
% pSig = feGet(fe,'psigfvoxelwisebyvoxel')
% pSig = feGet(fe,'psigfvoxelwisebyvoxel',coords)
% pSig = feGet(fe,'psigfvoxelwisebyvoxel',voxelIndices)
%---------
% The fiber and isotropic weights as a long vector
% w = feGet(fe,'fullweights')
%---------
% Return the global R2 (fraction of variance explained) of the full life
% model.
% R2 = feGet(fe,'total r2');
%---------
% Percent variance explained
% R2 = feGet(fe,'explained variance')
%---------
% Root mean squared error of the LiFE fit to the whole data
% rmse = feGet(fe,'rmse')
%---------
% Residual signal: (fiber prediction - measured_demeaned).
% res = feGet(fe,'res sig fiber')
%---------
% Residual signal: (full model prediction - measured signal).
% res = feGet(fe,'res sig full');
%---------
% Residual signal: (fiber model prediction - demeaned measured signal)
% with added mean signal. Res is returned as a vector.
% This is used to reconstruct an image (volume) to be used for the
% refinement process.
% res = feGet(fe,'fiber res sig with mean');
% res = feGet(fe,'fiber res sig with mean',coords);
% res = feGet(fe,'fiber res sig with mean',voxelIndices);
%---------
% Residual signal fiber model prediction - demeaned measured signal
% with added mean signal. Res is returned as an array (nBvecs x nVoxel).
% This is used to reconstruct an image (volume) to be used for the
% refinement process.
% res = feGet(fe,'fiber res sig with mean voxel');
% res = feGet(fe,'fiber res sig with mean voxel',coords);
% res = feGet(fe,'fiber res sig with mean voxel',voxelIndices);
%---------
% Predicted signal by the fiber model in a set of voxels.
% Vox subfield stores per voxel within the VOI. The pSig has size of the
% dwi. - It is stored as val = pSig(X,Y,Z,Theta)
%
% pSig = feGet(fe, 'pSig fiber by voxel');
% pSig = feGet(fe, 'pSig fiber by voxel',coords);
% pSig = feGet(fe, 'pSig fiber by voxel',voxelIndex);
%---------
% Return a column vector of the proportion of variance explained in
% each voxel.
% R2byVox = feGet(fe,'voxr2');
% R2byVox = feGet(fe,'voxr2',coords);
%---------
% Return a column vector of the proportion of variance explained in
% each voxel. (Normalized to the squared mean diffusion signal in each voxel)
% R2byVox = feGet(fe,'voxr2zero');
% R2byVox = feGet(fe,'voxr2zero',coords);
%---------
% Return the percent of varince explained in each voxel.
% R2byVox = feGet(fe,'var exp by voxel');
% R2byVox = feGet(fe,'var exp by voxel',coords);
%---------
% Demeaned diffusion signal in each voxel.
% dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel');
% dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',coords);
% dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',vxIndex);
%---------
% Full (measured) signal in each voxel.
% dSigByVoxel = feGet(fe,'dSig full by Voxel');
% dSigByVoxel = feGet(fe,'dSig full by Voxel',coords);
% dSigByVoxel = feGet(fe,'dSig full by Voxel',vxIndex);
%---------
% Predicted signal by the full model in a set of voxeles.
% pSigByVoxel = feGet(fe, 'pSig full by voxel');
% pSigByVoxel = feGet(fe, 'pSig full by voxel',coords);
% pSigByVoxel = feGet(fe, 'pSig full by voxel',voxelIndex);
%---------
% A volume of RMSE values.
% RMSE = feGet(fe,'vox rmse')
% RMSE = feGet(fe,'vox rmse',coords)
% RMSE = feGet(fe,'vox rmse',vxIndex)
%---------
% A volume of RMSE values with a subset of fibers' weights set to 0.
% RMSE = feGet(fe,'vox rmse',fiberIndices)
% RMSE = feGet(fe,'vox rmse',fiberIndices,coords)
% RMSE = feGet(fe,'vox rmse',fiberIndices,voxelIndex)
%---------
% Fibers' residual signal by voxel.
% res = feGet(fe,'res sig fiber vox')
% res = feGet(fe,'res sig fiber vox',coords)
% res = feGet(fe,'res sig fiber vox',vxIndex)
%---------
% Full (measured) residual signal by voxel.
% res = feGet(fe,'res sig full vox')
% res = feGet(fe,'res sig full vox',coords)
% res = feGet(fe,'res sig full vox',vxIndex)
%---------
% Fibers' residual signal by voxel with mean signal added (with added
% isotropic component).
% This is used to compute the residual signal for the refinement.
% res = feGet(fe,'fiber res sig with mean vox')
% res = feGet(fe,'fiber res sig with mean vox',coords)
% res = feGet(fe,'fiber res sig with mean vox',vxIndex)
%---------
% Residual signal full model prediction from a multi-voxel fit.
% res = feGet(fe,'res sig full voxfit');
% res = feGet(fe, 'res sig full voxfit',coords);
% res = feGet(fe, 'res sig full voxfit',voxelIndex);
%---------
% Fiber density statistics.
% Computes the fiber density (how many fibers in each voxel)
% We compute the following values:
% (1) The number of fibers in each voxel
% (2) The number of unique fibers with non-zero weights
% (3) The sum of the weights in each voxel
% (4) The mean of the weights in each voxel
% (5) The variance of the weigths in each voxel
% pSig = feGet(fe,'fiberdensity');
%---------
% Given an VOI or a set of indices to voxels returns the indices of the matching voxels inside the big
% volume, which ordinarily represents the full connectome.
% voxelIndices = feGet(fe,'voxelsindices',coords)
%                IMPORTANT: Size(coords) must be Nx3;
% voxelIndices = feGet(fe,'voxelsindices',voxelIndices)
%                IMPORTANT: Indices MUST be a column vector for this
%                code to work. Size(voxelIndices) = Nx1;
%---------
% Given an VOI finds the indices of the matching voxels inside the big
% volume, which ordinarily represents the full connectome.
%
% foundVoxels = feGet(fe,'find voxels',coords)
%
% coords is a Nx3 set of coordinates in image space
% foundVoxels is a vector of 1's and 0's, there is a one for each
% location the the connectome coordinates for which there is a match in
% the coords
%---------
% Given a set of VOI coords finds the row numbers of the Model matrix
% (or equivalently the dSig vector) that represent the data for this
% set of VOI coords.
% foundVoxels = feGet(fe,'coords 2 rows',coords)
% coords      - a Nx3 set of coordinates in image space
% foundVoxels - a binary vector that is 1 for each Model matrix row
%               that corresponds to at least one of the coords.
%---------
% Quaternian transformation from IMAGE space to ACPC space.
% xform = feGet(fe,'xform')
%---------
% Quaternian transformation from ACPC space to IMAGE space.
% xform = feGet(fe,'xform')
%---------
% Dimensions of the DW volume.
% dim = feGet(fe,'dims')
%---------
% Dimensions of the maps of parameters and results.
% dims = feGet(fe, 'mapsize')
%---------
% Path to the 3D Anatomy Volume.
% anatomyfile = feGet(fe, 't1 file')
%
% End of feGet.m parameters,
%
% Franco Pestilli (c) Stanford Vista Team 2012
val = [];
% Format the input parameters.
param = lower(strrep(param,' ',''));
% Start sorting the input and computing the output.
switch param
  case 'name'
    % Name of the current fe structure.
    %
    % name = feGet(fe,'name')
    val = fe.name;
  case 'type'
    % The type of objes (always, fascicle evaluation)
    %
    % type = feGet(fe,'type')
    val = fe.type; % Always fascicle evaluation
    % Set top level structure, not just single slot
  case 'life'
    % Structure of parameters and results from LIFE analysis
    %
    % life = feGet(fe,'life')
    val = fe.life;
  case {'fgimg','fibersimg'}
    % Return the connectome (fiber group) in image coordinates.
    %
    % fg = feGet(fe,'fg img')
    val = fe.fg;  % Fiber group candidate fascicles, uses fgSet/Get
  case {'fgacpc','fibersacpc'}
    % return the connectome in acpc coordinates.
    %
    % fg  = feGet(fg,'fg acpc')
    xform = feGet(fe,'img2acpcxform');
    val   = dtiXformFiberCoords(feGet(fe,'fgimg'),xform,'acpc');
  case 'roi'
    % Return the VOI comprised by the full connectome.
    %
    % roi = feGet(fe,'roi')
    val = fe.roi;
  case 'roiacpc'
    % Return the VOI comprised by the full connectome.
    %
    % roi = feGet(fe,'roi acpc')
    name   = sprintf('roi_%s',fe.fg.name);
    randColor = rand(1,3);
    val = dtiNewRoi(name,randColor,fefgGet(feGet(fe,'fg acpc'),'unique image coords'));
  case 'xform'
    % Transforms between coords for fg, roi, and dwi data
    %
    % xform = feGet(fe,'xform')
    val = fe.life.xform;
  case 'dwi'
    %  Load the diffusion weighted data.
    %
    % dwi = feGet(fe,'dwi')
    val = dwiLoad(feGet(fe,'dwifile'));
  case 'dwirepeat'
    %  Load the diffusion weighted data.
    %
    % dwi = feGet(fe,'dwirepeat')
    val = dwiLoad(feGetRep(fe,'dwifile'));
  case 'dwifile'
    %  Load the diffusion weighted data.
    %
    % dwiFile = feGet(fe,'dwifile')
    val = fe.path.dwifile;
  case 'dwifilerep'
    %  Load the diffusion weighted data.
    %
    % dwiFile = feGet(fe,'dwifilerep')
    val = fe.path.dwifilerep;
  case 'savedir'
    %  Directory where the LiFe structes are saved by defualt.
    %
    % sdir = feGet(fe,'savedir');
    val = fe.path.savedir;
  case {'bvecs'}
    % Diffusion directions.
    %
    % val = feGet(fe,'bvecs');
    val = fe.life.bvecs;
  case {'bvecsindices'}
    % Indices to the diffusion directions in the DWi 4th Dimension.
    %
    % val = feGet(fe,'bvecs indices');
    val = fe.life.bvecsindices;
  case {'nbvecs','nbvals'}
    % Number of B0's
    %
    % val = feGet(fe,'n bvals');
    val = length(feGet(fe,'bvals'));
  case {'bvals'}
    % B0 Values.
    %
    % bval = feGet(fe,'bvals')
    val = fe.life.bvals;
  case {'diffusionsignalinvoxel','dsiinvox','dsigvox','dsigmeasuredvoxel'}
    % Returns a nVoxels X nBvecs array of measured diffusion signal
    %
    % val = feGet(fe,'dsiinvox');
    % val = feGet(fe,'dsiinvox',voxelsIndices);
    % val = feGet(fe,'dsiinvox',coords);
    val = fe.life.diffusion_signal_img(feGet(fe,'voxelsindices',varargin),:)';
  case {'diffusionsignalinvoxeldemeaned','dsiinvoxdemeaned'}
    % Returns a nVoxels X nBvecs array of demeaned diffusion signal
    %
    % val =feGet(fe,'dsiinvoxdemeaned');
    % val =feGet(fe,'dsiinvoxdemeaned',voxelsIndices);
    % val =feGet(fe,'dsiinvoxdemeaned',coords);
    nBvecs     = feGet(fe,'nBvecs');
    voxelIndices = feGet(fe,'voxelsindices',varargin);
    val = fe.life.diffusion_signal_img(voxelIndices,:) - repmat(mean(fe.life.diffusion_signal_img(voxelIndices,:), 2),1,nBvecs);
    keyboard
    % THis seems to be wrong
  case {'b0signalimage','b0vox'}
    % Get the diffusion signal at 0 diffusion weighting (B0) for this voxel
    %
    % val = feGet(fe,'b0signalvoxel');
    % val = feGet(fe,'b0signalvoxel',voxelIndex);
    % val = feGet(fe,'b0signalvoxel',coords);
    val = fe.life.diffusion_S0_img(feGet(fe,'voxelsindices',varargin), :);
  case {'fiberssubset','fsub','subsetoffibers','fgsubset'}
    % Return a subset of fibers from the conenctome.
    %
    % fg = feGet(fe,'fiberssubset',fiberList);
    val = feGet(fe,'fg img');
    fiberList = varargin{1};
    fibers = cell(size(fiberList));
    for ff = 1:length(fiberList)
      fibers{ff} = val.fibers{fiberList(ff)};
      if isfield(val,'pathwayInfo')
        pathInfo(ff) = val.pathwayInfo(fiberList(ff));
      end
    end
    val.fibers = fibers;
    if isfield(val,'pathwayInfo')
      val.pathwayInfo = pathInfo;
    end
    val.name = sprintf('subsetFrom:%s',val.name);
  case {'roivoxels','roicoords'}
    % Return the coordinates of the VOI comprised in the connectome.
    % Always in image space.
    %
    % coords = feGet(fe,'roi coords')
    val = fe.roi.coords;
  case {'roicoordssubset'}
    % Return the coordinates of the VOI comprised in the connectome.
    % Always in image space.
    %
    % coords = feGet(fe,'roi coords')
    val = feGet(fe,'roi coords');
    val = val(varargin{1},:);
  case {'nroivoxels','nvoxels'}
    % Number of voxels in the connectome/VOI.
    %
    % nVoxels = feGet(fe,'n voxels')
    val = size(feGet(fe,'roivoxels'),1);
  case {'usedvoxels','indexesofusedvoxels'}
    % Indexes of actually used voxels.
    %
    % These can be different than the number of voxels in the VOI in case some
    % voxels have no fibers in them.
    %
    % TO BE DEPRECATED.
    %
    % indxUsedVx = feGet(fe,'index of used voxels')
    val = find(feGet(fe,'nnodes'));
  case {'nusedvoxels','numberofusedvoxels'}
    % Number of actually used voxels.
    %
    % This can be less than the number of voxels in the VOI in case some
    % voxels have no fibers in them.
    %
    % TO BE DEPRECATED.
    %
    % nUsedVx = feGet(fe,'index of used voxels')
    val = size(feGet(fe,'used voxels'),2);
  case {'startrow','first index into the dsig vector for a voxel'}
    % Returns the first index to a voxel in the dSig vector.
    %
    % The dSig vector is 1:nBvecs*nVoxels.
    %
    % val = feGet(fe,'start rows')
    val = (varargin{1}-1)*feGet(fe,'nBvecs') + 1;
  case {'voxelrows','all indexes into the dsig vector for a set of voxels'}
    % Return the rows corresponding to a set of voxels.
    %
    % rows = feGet(fe,'voxel rows',idxVoxel)
    n        = feGet(fe,'n voxels');
    nBvecs   = feGet(fe,'n bvecs');
    voxelsToKeep = zeros(n,1); voxelsToKeep(varargin{1}) = 1;
    val = logical(kron(voxelsToKeep(:),ones(nBvecs,1)));
  case {'modeltensor'}
    val = fe.life.modelTensor;
  case {'mfiber','m','model'}
    % Return the model (M matrix), or a subset of it.
    %
    % Mfiber = feGet(fe,'M fiber');
    % Mfiber = feGet(fe,'model',voxelsIndices);
    % Mfiber = feGet(fe,'model',coords);
    % idxVoxels is an integer list of the voxels to retain
    % If idxVoxels is not included, return the whole matrix
    % M contains only the rows for the specified voxels (all directions)
    if isempty(varargin)
      % Return the whole M matrix
      val = fe.life.Mfiber;
    else
      % Return only the rows for the specified voxels, including all
      % directions.
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val = fe.life.Mfiber(voxelRowsToKeep,:);
      val = fe.life.Mfiber(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)),:);
    end
  case {'mfibervoxelsubset','indexedafiber','mfiberindexed'}
    % Return a subset of measurements from the fiber portion of M matrix
    % The rows of M are specified.  Remember that the rows refer to a
    % combination of voxel and measurement direction and potentially in the
    % future a b-value.  Hence, the rows are not specific to a voxel.
    %
    % Mfiber = feGet(fe,'mfiber subset',rowsToKeep);
    if isempty(varargin), error('Subset of rows must be specified'); end
    val = fe.life.Mfiber(varargin{1},:);
  case {'msubsetfibers','mfiberssubset','mkeepfibers'}
    % Returns the model (M) with only a subset of columns (fibers).
    %
    % fiberList is a vector of indexes, e.g, [1 10 100]
    %
    % M = feGet(fe,'mkeepfibers',fiberList)
    val = fe.life.Mfiber(:,varargin{1});
  case {'miso'}
    % Isotropic portion of M matrix
    % returns the matrix for the full model or for a subset of voxels
    %
    % Miso = feGet(fe,'M iso')
    % Miso = feGet(fe,'M iso',voxelsIndices)
    % Miso = feGet(fe,'M iso',coords)
    if isempty(varargin)
      % Return the whole M iso
      val = feBuildSparseBlockDiag(feGet(fe,'nBvecs'),feGet(fe,'nVoxels'));
    else
      val = feBuildSparseBlockDiag(feGet(fe,'nBvecs'),length(feGet(fe,'voxelsindices',varargin)));
    end
  case {'voxel2fnpair','voxel2fibernodepair','v2fnp'}
    % Pairing of fibers and nodes in each voxel.
    %
    % v2fnp = feGet(fe,'v2fnp');
    if isempty(fe.life.voxel2FNpair)
      fprintf('[%s] fe.life.voxel2FNpair is empty, can be computed as: \nfe = feSet(fe,''v2fnp'',feGet(fe,''fg img''),''v2fn'',feGet(fe,''roi coords'')',mfilename);
      return
    end
    val = fe.life.voxel2FNpair;
  case {'tensors','fibers tensors'}
    % Tensors computed for each node and fiber in a set of voxels.
    %
    % t = feGet(fe,'tensors')
    % t = feGet(fe,'tensors',voxelsIndices);
    % t = feGet(fe,'tensors',coords);
    if isempty(varargin)
      val = fe.life.fibers.tensors;
    else
      vv = feGet(fe,'voxelsindices',varargin);
      val = cell(size(vv));
      for ff = 1:length(vv)
        val{ff} = fe.life.fibers.tensors{vv(ff)};
      end
    end
  case {'voxeltensors','voxtensors','voxq'}
    % Get all the tensors in a signle voxel
    %
    % val = feGet(fe,'voxtensors',voxelIndex)
    % val = feGet(fe,'voxtensors',coord)
    % Index for the voxel
    vv = feGet(fe,'voxelsindices',varargin);
    % The indexes of the voxeles used, to build LiFE.
    usedVoxels = feGet(fe,'usedVoxels');
    voxIndex   = usedVoxels(vv);
    nNodes     = feGet(fe,'nNodes');
    % Get the tensors for each node in each fiber going through this voxel:
    val = zeros(nNodes(voxIndex), 9); % Allocate space for all the tensors (9 is for the 3 x 3 tensor components)
    for ii = 1:nNodes(voxIndex)           % Get the tensors
      val(ii,:) = fe.life.fibers.tensors{fe.life.voxel2FNpair{voxIndex}(ii,1)} ...
        (fe.life.voxel2FNpair{voxIndex}(ii,2),:);
    end
  case {'nnodes','numofnodes'}
    % Total number of nodes in each voxel The voxel2FN pairs are row size
    % equals number of nodes and column size is always 2. The entries of
    % the first column are the fiber number. The entries in the second
    % column are the node of the fiber inside the voxel.
    %
    % val = feGet(fe,'n nodes');
    % val = feGet(fe,'n nodes',voxelsIndices);
    % val = feGet(fe,'n nodes',coords);
    if ~isempty(fe.life.voxel2FNpair)
        [val, ~] = cellfun(@size,fe.life.voxel2FNpair);
        val      = val(feGet(fe,'voxelsindices',varargin));
    end
  case {'numberofuniquefibersbyvoxel','uniquefnum'}
    % Return the total number of fibers for all the voxels or in a set of
    % voxels
    %
    % nFibers = feGet(fe,'uniquefnum');           % all the voxels
    % nFibers = feGet(fe,'uniquefnum',[1 2 3 4]); % for some the voxels,
    %                                             % specified by indexes
    % nFibers = feGet(fe,'uniquefnum',coords);    % for some the voxels,
    %                                             % specified by coordinates
    val = fe.life.fibers.unique.num(feGet(fe,'voxelsindices',varargin));
  case {'indextouniquefibersbyvoxel','uniquef'}
    % Return the indexes of the fibers for all the voxels or in a set of
    % voxels.
    %
    % idxFibers = feGet(fe,'uniquef');           % all the voxels
    % idxFibers = feGet(fe,'uniquef',[1 2 3 4]); % for some the voxels,
    %                                            % specified by indexes
    % idxFibers = feGet(fe,'uniquef',coords);    % for some the voxels,
    %                                            % specified by coordinates
    vxIndex = feGet(fe,'voxels indices',varargin);
    val = cell(length(vxIndex),1);
    for ii = 1:length(vxIndex)
      val{ii} = fe.life.fibers.unique.index{vxIndex(ii)};
    end
  case {'numberoftotalfibersbyvoxels','totfnum'}
    % Return the total number of fibers for all the voxels or in a set of
    % voxels
    %
    % nFibers = feGet(fe,'totfnum');           % all the voxels
    % nFibers = feGet(fe,'totfnum',[1 2 3 4]); % for some the voxels,
    %                                          % specified by indexes
    % nFibers = feGet(fe,'totfnum',coords);    % for some the voxels,
    %                                          % specified by coordinates
    val = fe.life.fibers.total.num(feGet(fe,'voxels indices',varargin));
  case {'indexoftotalfibersbuvoxel','totf'}
    % Return the indexes of the fibers for all the voxels or in a set of
    % voxels
    %
    % idxFibers = feGet(fe,'totf');             % all the voxels
    % idxFibers = feGet(fe,'totf',[1 2 3 4]);   % for some the voxels,
    %                                           % specified by indexes
    % idxFibers = feGet(fe,'totfibers',coords); % for some the voxels,
    %                                           % specified by coordinates
    vxIndex = feGet(fe,'voxels indices',varargin);
    val = cell(length(vxIndex),1);
    for ii = 1:length(vxIndex)
      val{ii} = fe.life.fibers.total.index{vxIndex(ii)};
    end
  case {'nfibers'}
    % Return the number of fibers in the model.
    %
    % nFibers = feGet(fe,'n fibers')
    val = size(fe.life.Mfiber,2);
  case {'isoweights','weightsiso','meanvoxelsignal'}
    % Weights of the isotropic voxel signals, this is the mean signal in
    % each voxel.
    %
    % val = feGet(fe,'iso weights');
    % val = feGet(fe,'iso weights'coords)
    % val = feGet(fe,'iso weights',voxelIndices)
    val = feGet(fe,'Miso') \ feGet(fe,'dsig full')';
    val = val(feGet(fe,'voxelsindices',varargin));
  case {'voxisoweights','voxweightsiso','voxmeanvoxelsignal'}
    % Weights of the isotropic voxel signals, this is the mean signal in
    % each voxel.
    % Organized nBvecs x nVoxels
    %
    % val = feGet(fe,'iso weights');
    % val = feGet(fe,'iso weights'coords)
    % val = feGet(fe,'iso weights',voxelIndices)
    val = feGet(fe,'Miso') \ feGet(fe,'dsig full')';
    val = repmat(val,1,feGet(fe,'nbvecs'))';
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val           = val(voxelRowsToKeep,:);
      val = val(:,feGet(fe,'voxelsindices',varargin));
    end
  case {'dsigiso','isodsig'}
    % mean signalin each voxel, returned for each diffusion direction:
    % size(nBvecsxnVoxels, 1).
    %
    % val = feGet(fe,'iso disg');
    % val = feGet(fe,'iso disg',coords)
    % val = feGet(fe,'iso dsig',voxelIndices)
    val = feGet(fe,'iso weights');
    val = repmat(val,1,feGet(fe,'nbvecs'))';
    val = val(:);
  case {'fiberweights'}
    % Weights of the fiber component. For all the fibers or a subset of
    % them.
    %
    % w = feGet(fe,'fiber weights')
    % w = feGet(fe,'fiber weights',fiberIndices)
    % If the model was not fit yet, fit it, install the fit and then return
    % the weights.
    if ~isfield(fe.life,'fit')
      fprintf('[%s] fe.life.fit is empty, can be computed as: \nfeSet(fe,''fit'',feFitModel(feGet(fe,''Mfiber''), feGet(fe,''dsigdemeaned''),''sgdnn''))',mfilename);
      return
    end
    % Get the weights
    if ~isempty(varargin) % subselect the weights for the requested fibers
      val = fe.life.fit.weights(varargin{1});
    else % Return all of them
      val = fe.life.fit.weights;
    end
  case {'fiberweightstest'}
    % Weights of the fiber component with a subset of the fibers' weigth
    % set to zero. This can be used to test the loss in RMSE for the
    % connectome when a subset of fibers is removed, but the connectome is
    % not fitted again.
    %
    % w = feGet(fe,'fiber weights test',fiberIndices)
    % If the model was not fit yet, fit it, install the fit and then return
    % the weights.
    if ~isfield(fe.life,'fit')
      fprintf('[%s] fe.life.fit is empty, can be computed as: \nfeSet(fe,''fit'',feFitModel(feGet(fe,''Mfiber''), feGet(fe,''dsigdemeaned''),''sgdnn''))',mfilename);
      return
    end
    % Get the weights
    if ~isempty(varargin) % subselect the weights for the requested fibers
      val = fe.life.fit.weights;
      val(varargin{1}) = 0;
    else % A set of fiber weights is required as input
      error('[%s] Indices to a subset of fiber-weights must be passed in w = feGet(fe,''fiber weights test'',fiberIndices))',mfilename);
    end
    case {'fiberweightstestvoxelwise'}
    % Weights of the fiber component with a subset of the fibers' weigth
    % set to zero. This can be used to test the loss in RMSE for the
    % connectome when a subset of fibers is removed, but the connectome is
    % not fitted again.
    %
    % w = feGet(fe,'fiber weights test voxel wise',fiberIndices)
    % If the model was not fit yet, fit it, install the fit and then return
    % the weights.
    if ~isfield(fe.life,'voxfit')
      fprintf('[%s] fe.life.fit is empty, can be computed as: \nfeSet(fe,''fit'',feFitModel(feGet(fe,''Mfiber''), feGet(fe,''dsigdemeaned''),''sgdnn''))',mfilename);
      return
    end
    % Get the weights
    if ~isempty(varargin) % subselect the weights for the requested fibers
      val = fe.life.voxfit.weights;
      val(:,varargin{1}) = 0;
    else % A set of fiber weights is required as input
      error('[%s] Indices to a subset of fiber-weights must be passed in\nw = feGet(fe,''fiber weights test voxel wise'',fiberIndices))',mfilename);
    end
  case {'dsigmeasured','dsigfull'}
    % Measured signal in VOI, this is the raw signal. not demeaned
    %
    % dSig = feGet(fe,'dSig full')
    val = fe.life.dSig;
    % Return a subset of voxels
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val              = val(voxelRowsToKeep,:);
      val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
    end
  case {'diffusionsignaldemeaned','dsigdemeaned'}
    % Measured signal in VOI, demeaned, this is the signal used for the
    % fiber-portion of the M model.
    %
    % dSig = feGet(fe,'dsigdemeaned');
    % dSig = feGet(fe,'dsigdemeaned',[1 10 100]);
    % dSig = feGet(fe,'dsigdemeaned',coords);
    nVoxels = feGet(fe,'nVoxels');
    nBvecs  = feGet(fe,'nBvecs');
    val     = (fe.life.dSig - reshape(repmat( ...
      mean(reshape(fe.life.dSig, nBvecs, nVoxels),1),...
      nBvecs,1), size(fe.life.dSig)))';
    % Return a subset of voxels
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val           = val(voxelRowsToKeep,:);
      val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
    end
  case {'dsigrowssubset','diffusionsignaldemeanedinsubsetofrows'}
    % Get the demeaned signal for a subset of rows.
    % Useful for cross-validation.
    %
    % dSig = feGet(fe,'dsigrowssubset',voxelsList);
    dSig = feGet(fe,'dsigdemeaned');
    for vv = 1:length(voxelsList)
      val(feGet(fe,'voxel rows',vv)) = dSig(feGet(fe,'voxel rows',voxelList(vv)));
    end
  case {'psigfiber', 'fiberpsig','fiberpredicted','dsigpredictedfiber'}
    % Predicted signal of fiber alone (demeaned).
    %
    % pSig = feGet(fe,'pSig fiber');
    % pSig = feGet(fe,'pSig fiber',coords);
    % pSig = feGet(fe,'pSig fiber',voxelIndices);
    val = feGet(fe,'Mfiber')*feGet(fe,'fiber weights');
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val           = val(voxelRowsToKeep,:);
      val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
    end
  case {'uniquefibersindicesinroi'}
    % Find the unique fibers indices in the FE roi.
    % Thisis necessary sometimes after changing the number of voxels in an
    % FE structure, as it is performed by feConnectomeReduceVoxels.m
    %
    % FibInRoi = feGet(fe,'uniquefibersinroi');
    % Get all the unique fibers in each voxel
    uniquefvx = fefgGet(feGet(fe,'fibers img'), ...
                        'uniquefibersinvox',     ...
                        feGet(fe,'roi coords'));
    val = [];
    for ivx = 1:length(uniquefvx)
        val = [val; uniquefvx{ivx}];
    end
    val = unique(val);
  case {'weightsinroi'}
    % Find the weights of the fibers in a specified volume.
    %
    % We compute the following values:
    % (1) The number of unique fibers in the volume
    % (2) The weights for the fibers in the roi
    %
    % wFibInRoi = feGet(fe,'weightsinroi');
    % Get all the unique fibers in each voxel
    FibInRoi = feGet(fe,'uniquefibersindicesinroi');
1000
1001     % extract the fber weights obtained in a LiFE fit
1002     w   = feGet(fe,'fiber weights');
1003
1004     % Return only the ones for the fibers in this roi
1005     val = w(unique(FibInRoi));
1006
1007   case {'fiberdensity'}
1008     % Fiber density statistics.
1009     %
1010     % Computes the fiber density (how many fibers in each voxel)
1011     %
1012     % We compute the following values:
1013     % (1) The number of fibers in each voxel
1014     % (2) The number of unique fibers with non-zero weights
1015     % (3) The sum of the weights in each voxel
1016     % (4) The mean of the weights in each voxel
1017     % (5) The variance of the weigths in each voxel
1018     %
1019     % pSig = feGet(fe,'fiberdensity');
1020
1021     % Get the unique fibers in each voxel
1022     uniquefvx = fefgGet(feGet(fe,'fibers img'), ...
1023                         'uniquefibersinvox',     ...
1024                         feGet(fe,'roi coords'));
1025
1026     % extract the fber weights obtained in a LiFE fit
1027     w = feGet(fe,'fiber weights');
1028
1029     % Compute the fiber density in three wasy:
1030     % (1) The number of fibers in each voxel
1031     % (2) The number of unique fibers with non-zero weights
1032     % (3) The sum of the weights in each voxel
1033     % (4) The mean of the weights in each voxel
1034     % (5) The variance of the weigths in each voxel
1035     val = nan(length(uniquefvx),5);
1036     for ivx = 1:length(uniquefvx)
1037
1038       % Number of fibers in each voxel
1039       val(ivx,1) = length(uniquefvx{ivx});
1040
1041       % Number of fibers in ech voxel with non-zero weight
1042       val(ivx,2) = length(uniquefvx{ivx}(w(uniquefvx{ivx}) > 0));
1043
1044       % Sum of fiber weights in each voxel
1045       val(ivx,3) = sum(w(uniquefvx{ivx}));
1046
1047       % Mean of fiber weights in each voxel
1048       val(ivx,4) = nanmedian(w(uniquefvx{ivx}));
1049
1050       % Var of fibers in each voxel
1051       val(ivx,5) = nanvar(w(uniquefvx{ivx}));
1052     end
1053
1054   case {'psigfibertest'}
1055     % Predicted signal (demeaned) with a subset of fibers' weights set to 0.
1056     % This can be used to test the loss in RMSE for the connectome when a
1057     % subset of fibers is removed, but the connectome is not fitted again.
1058     %
1059     % pSig = feGet(fe,'pSig fiber test',fiberIndices);
1060     % pSig = feGet(fe,'pSig fiber test',fiberIndices,voxelIndices);
1061     % pSig = feGet(fe,'pSig fiber test',fiberIndices,coords);
1062     if ~isempty(varargin)
1063       val = feGet(fe,'Mfiber')*feGet(fe,'fiber weights test',varargin{1});
1064
1065       % Now select a subset of voxels if requested
1066       if (length(varargin) == 2)
1067         % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1068         % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1069         % val               = val(voxelRowsToKeep,:);
1070         val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin{2})));
1071       end
1072     else
1073       error('[%s] A set f fiber indiced must be passed in. pSig = feGet(fe,''pSig fiber test'',fiberIndices))',mfilename);
1074     end
1075
1076   case {'psigfibertestvoxelwise'}
1077     % Predicted signal (demeaned) with a subset of fibers' weights set to 0.
1078     % This can be used to test the loss in RMSE for the connectome when a
1079     % subset of fibers is removed, but the connectome is not fitted again.
1080     %
1081     % pSig = feGet(fe,'pSig fiber test voxel wise',fiberIndices);
1082     % pSig = feGet(fe,'pSig fiber test voxel wise',fiberIndices,voxelIndices);
1083     % pSig = feGet(fe,'pSig fiber test voxel wise',fiberIndices,coords);
1084
1085     if ~isempty(varargin)
1086       nVoxels = feGet(fe,'nvoxels');
1087       w = feGet(fe,'fiber weights test voxel wise',varargin{1}); % Weights with a subset set to 0
1088       % Handling parallel processing
1089       poolwasopen=1; % if a matlabpool was open already we do not open nor close one
1090       if (matlabpool('size') == 0), matlabpool open; poolwasopen=0; end
1091       val = cell(nVoxels,1);
1092       for ivox = 1:nVoxels
1093         % Predict the signal.
1094         val{ivox} = feGet(fe,'Mfiber',ivox)*w(ivox,:)';
1095       end
1096
1097       % Handling parallel processing.
1098       if ~poolwasopen, matlabpool close; end
1099       fprintf('done in %2.3fminutes.\n',toc/60)
1100
1101       % Reorganize the signal into a vector
1102       val = vertcat(val{:})';
1103
1104       % Now select a subset of voxels if requested
1105       if (length(varargin) == 2)
1106         % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1107         % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1108         % val               = val(voxelRowsToKeep,:);
1109         val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin{2})));
1110       end
1111     else
1112       error('[%s] A set f fiber indiced must be passed in. pSig = feGet(fe,''pSig fiber test'',fiberIndices))',mfilename);
1113     end
1114
1115   case {'predictedsignalfull','psigfull'}
1116     % Predicted measured signal from both fiber and iso
1117     %
1118     % pSig = feGet(fe,'pSig full')
1119     % pSig = feGet(fe,'pSig full',coords)
1120     % pSig = feGet(fe,'pSig full',voxelIndices)
1121     val = [feGet(fe,'M fiber'), feGet(fe,'M iso')] * feGet(fe,'full weights');
1122     if ~isempty(varargin)
1123       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1124       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1125       % val           = val(voxelRowsToKeep,:);
1126       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1127     end
1128
1129   case {'fullweights'}
1130     % The fiber and isotropic weights as a long vector
1131     %
1132     % w = feGet(fe,'fullweights')
1133     val = [feGet(fe,'fiber weights'); feGet(fe,'iso weights')];
1134
1135   case {'fiberweightsvoxelwise'}
1136     % The woxels returned by a fit of LiFE by voxel/fiber
1137     %
1138     % w = feGet(fe,'fiberweightsvoxelwise')
1139     val = fe.life.voxfit.weights;
1140
1141   case {'psigfvoxelwise'}
1142     % Predict the diffusion signal for the fiber component
1143     % with the voxel-wise fit of LiFE
1144     %
1145     % pSig = feGet(fe,'psigfvoxelwise')
1146     % pSig = feGet(fe,'psigfvoxelwise',coords)
1147     % pSig = feGet(fe,'psigfvoxelwise',voxelIndices)
1148
1149     if ~isfield(fe.life,'voxfit'),
1150       error('[%s] Cannot find voxel-wise fit.\nTo fit the model voxel-wise run:\nfe = feFitModelByVoxel(fe)\n',mfilename);
1151     end
1152     val = fe.life.voxfit.psig;
1153
1154     % Get a subset of voxels.
1155     if ~isempty(varargin)
1156       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1157       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1158       % val           = val(voxelRowsToKeep,:);
1159       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1160     end
1161
1162   case {'psigfvoxelwisebyvoxel'}
1163     % Predict the diffusion signal for the fiber component
1164     % with the voxel-wise fit of LiFE, return the an array of pSigXnVoxel
1165     %
1166     % pSig = feGet(fe,'psigfvoxelwisebyvoxel')
1167     % pSig = feGet(fe,'psigfvoxelwisebyvoxel',coords)
1168     % pSig = feGet(fe,'psigfvoxelwisebyvoxel',voxelIndices)
1169     nBvecs  = feGet(fe,'nBvecs');
1170     nVoxels = feGet(fe,'n voxels');
1171     val     = reshape(feGet(fe,'psigfvoxelwise'), nBvecs, nVoxels);
1172
1173   case {'totalr2'}
1174     % Return the global R2 (fraction of variance explained) of the full life
1175     % model.
1176     %
1177     % R2 = feGet(fe,'total r2');
1178
1179     %     measured  = feGet(fe,'dsigdemeaned');
1180     %     predicted = feGet(fe,'fiber p sig');
1181     %     val = (1 - (sum((measured - predicted).^2) ./ ...
1182     %                 sum((measured - mean(measured)).^2)));
1183     val = (1 - (sum((feGet(fe,'diffusion signal demeaned') - ...
1184       feGet(fe,'fiber predicted')).^2) ./ ...
1185       sum((feGet(fe,'diffusion signal demeaned') - ...
1186       mean(feGet(fe,'diffusion signal demeaned'))).^2)));
1187
1188   case {'totalr2voxelwise'}
1189     % Return the global R2 (fraction of variance explained) of the full life
1190     % model from a voxel-wise fit.
1191     %
1192     % R2 = feGet(fe,'total r2 vocel wise');
1193
1194     %     measured  = feGet(fe,'dsigdemeaned');
1195     %     predicted = feGet(fe,'p sig f voxel wise');
1196     %     val = (1 - (sum((measured - predicted).^2) ./ ...
1197     %                 sum((measured - mean(measured)).^2)));
1198     val = (1 - (sum((feGet(fe,'diffusion signal demeaned') - ...
1199       feGet(fe,'psigfvoxelwise')').^2) ./ ...
1200       sum((feGet(fe,'diffusion signal demeaned') - ...
1201       mean(feGet(fe,'diffusion signal demeaned'))).^2)));
1202
1203   case {'totpercentvarianceexplained','totpve'}
1204     % Percent variance explained
1205     %
1206     % R2 = feGet(fe,'explained variance')
1207     val = 100 * feGet(fe,'total r2');
1208
1209   case {'rmsetotal','totalrmse'}
1210     % Root mean squared error of the LiFE fit to the whole data
1211     %
1212     % rmse = feGet(fe,'rmse')
1213     val = sqrt(mean((feGet(fe,'diffusion signal demeaned') - ...
1214       feGet(fe,'pSig fiber')).^2));
1215
1216   case {'totalrmsevoxelwise'}
1217     % Root mean squared error of the LiFE fit to the whole data from a
1218     % vocel-wise fit
1219     %
1220     % rmse = feGet(fe,'rmse')
1221     val = sqrt(mean((feGet(fe,'diffusion signal demeaned') - ...
1222       feGet(fe,'pSig f voxelwise')').^2));
1223
1224   case {'ressigfiber'}
1225     % Residual signal fiber prediction - measured_demeaned.
1226     %
1227     % res = feGet(fe,'res sig fiber')
1228     val = (feGet(fe,'dsigdemeaned')    - feGet(fe,'psig fiber'));
1229     if ~isempty(varargin)
1230       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1231       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1232       % val              = val(voxelRowsToKeep,:);
1233       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1234     end
1235
1236   case {'ressigfull'}
1237     % Residual signal full model prediction - measured signal.
1238     %
1239     % res = feGet(fe,'res sig full');
1240     % res = feGet(fe, 'res sig full',coords);
1241     % res = feGet(fe, 'res sig full',voxelIndex);
1242     val = (feGet(fe,'dsig full')    - feGet(fe,'psig full')');
1243     if ~isempty(varargin)
1244       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1245       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1246       % val           = val(voxelRowsToKeep,:);
1247       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1248     end
1249
1250   case {'ressigfullvoxelwise'}
1251     % Residual signal full model prediction from a multi-voxel fit.
1252     %
1253     % res = feGet(fe,'res sig full voxfit');
1254     % res = feGet(fe, 'res sig full voxfit',coords);
1255     % res = feGet(fe, 'res sig full voxfit',voxelIndex);
1256     %tic,val      = feGet(fe,'dsig demeaned') - feGet(fe,'psigfvoxelwise') + feGet(fe,'dsigiso');toc
1257     val      = feGet(fe,'dsig full') - feGet(fe,'psigfvoxelwise')';
1258     if ~isempty(varargin)
1259       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1260       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1261       % val           = val(voxelRowsToKeep,:);
1262       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1263     end
1264
1265   case {'fiberressigwithmean'}
1266     % Residual signal fiber model prediction - demeaned measured signal
1267     % with added mean signal. VECTOR FORM.
1268     %
1269     % This is used to reconstruct an image (volume) to be used for the
1270     % refinement process.
1271     %
1272     % res = feGet(fe,'fiber res sig with mean');
1273
1274     % predicted = feGet(fe,'psig fiber');
1275     % measured  = feGet(fe,'dsigdemeaned');
1276     % val = (measured_full - predicted demeaned);
1277     val = (feGet(fe,'dsig full')' - feGet(fe,'psig fiber'));
1278
1279     if ~isempty(varargin)
1280       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1281       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1282       % val           = val(voxelRowsToKeep,:);
1283       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1284     end
1285
1286   case {'predictedfibersignalvoxel','psigfvox'}
1287     % Predicted signal by the fiber model in a set of voxels.
1288     %
1289     % Vox subfield stores per voxel within the VOI
1290     % The pSig has size of the dwi.
1291     % It is stored as val = pSig(X,Y,Z,Theta)
1292     %
1293     % pSig = feGet(fe, 'pSig fiber by voxel');
1294     % pSig = feGet(fe, 'pSig fiber by voxel',coords);
1295     % pSig = feGet(fe, 'pSig fiber by voxel',voxelIndex);
1296     nBvecs  = feGet(fe,'nBvecs');
1297     nVoxels = feGet(fe,'n voxels');
1298     val     = reshape(feGet(fe,'pSig fiber'), nBvecs, nVoxels);
1299     val     = val(:,feGet(fe,'return voxel indices',varargin));
1300
1301   case {'predictedfullsignalvoxel','psigfullvox'}
1302     % Predicted signal by the full model in a set of voxeles.
1303     %
1304     % Vox subfield stores per voxel within the VOI
1305     % The pSig has size of the dwi.
1306     % It is stored as val = pSig(X,Y,Z,Theta)
1307     %
1308     % pSig = feGet(fe, 'pSig full by voxel');
1309     % pSig = feGet(fe, 'pSig full by voxel',coords);
1310     % pSig = feGet(fe, 'pSig full by voxel',voxelIndex);
1311     nBvecs  = feGet(fe,'nBvecs');
1312     nVoxels = feGet(fe,'n voxels');
1313     val     = reshape(feGet(fe,'pSig full'), nBvecs, nVoxels);
1314
1315   case {'voxelr2','r2vox','voxr2','r2byvoxel'}
1316     % Return a column vector of the proportion of variance explained in
1317     % each voxel.
1318     %
1319     % R2byVox = feGet(fe,'voxr2');
1320     % R2byVox = feGet(fe,'voxr2',coords);
1321     measured  = feGet(fe,'dSig demeaned by voxel');
1322     predicted = feGet(fe,'pSig f vox');
1323     nBvecs    = feGet(fe,'nBvecs');
1324     val       = (1 - (sum((measured - predicted).^2) ./ ...
1325       sum((measured - repmat(mean(measured), nBvecs,1)).^2)));
1326     val       = val(feGet(fe,'return voxel indices',varargin));
1327
1328   case {'voxelr2zero','r2voxzero','voxr2zero','r2byvoxelzero'}
1329     % Return a column vector of the proportion of variance explained in
1330     % each voxel. (Normalized to the squared diffusion signal in each voxel)
1331     %
1332     % R2byVox = feGet(fe,'voxr2zero');
1333     % R2byVox = feGet(fe,'voxr2zero',coords);
1334     measured  = feGet(fe,'dSig demeaned by voxel');
1335     predicted = feGet(fe,'pSig f vox');
1336     val       = (1 - (sum((measured - predicted).^2) ./ sum(measured.^2)));
1337     val       = val(feGet(fe,'return voxel indices',varargin));
1338
1339   case {'voxelvarianceexplained','varexpvox','voxvarexp','varexpbyvoxel'}
1340     % Return the percent of varince explained in each voxel.
1341     %
1342     % R2byVox = feGet(fe,'var exp by voxel');
1343     % R2byVox = feGet(fe,'var exp by voxel',coords);
1344     val = 100.*feGet(fe,'voxr2');
1345     val = val(feGet(fe,'return voxel indices',varargin));
1346
1347   case {'voxelr2voxelwise','r2voxvoxelwise','voxr2voxelwise'}
1348     % Return a column vector of the proportion of variance explained in
1349     % each voxel.
1350     %
1351     % R2byVox = feGet(fe,'voxr2voxelwise');
1352     % R2byVox = feGet(fe,'voxr2voxewise',coords);
1353     measured  = feGet(fe,'dSig demeaned by voxel');
1354     predicted = feGet(fe,'psig f voxel wise by voxel');
1355     nBvecs    = feGet(fe,'nBvecs');
1356     val       = (1 - (sum((measured - predicted).^2) ./ ...
1357       sum((measured - repmat(mean(measured), nBvecs,1)).^2)));
1358     val       = val(feGet(fe,'return voxel indices',varargin));
1359
1360   case {'voxelr2zerovoxelwise','voxr2zerovoxelwise'}
1361     % Return a column vector of the proportion of variance explained in
1362     % each voxel. (Normalized to the squared diffusion signal in each voxel)
1363     %
1364     % R2byVox = feGet(fe,'voxr2zerovoxelwise');
1365     % R2byVox = feGet(fe,'voxr2zerovoxelwise',coords);
1366     measured  = feGet(fe,'dSig demeaned by voxel');
1367     predicted = feGet(fe,'psig f voxel wise by voxel');
1368     val       = (1 - (sum((measured - predicted).^2) ./ sum(measured.^2)));
1369     val       = val(feGet(fe,'return voxel indices',varargin));
1370
1371   case {'voxelvarianceexplainedvoxelwise','varexpvoxvoxelwise'}
1372     % Return the percent of varince explained in each voxel.
1373     %
1374     % R2byVox = feGet(fe,'var exp by voxel');
1375     % R2byVox = feGet(fe,'var exp by voxel',coords);
1376     val = 100.*feGet(fe,'voxr2voxelwise');
1377     val = val(feGet(fe,'return voxel indices',varargin));
1378
1379   case {'dsigdemeanedbyvoxel','dsigdemeanedvox'}
1380     % Demeaned diffusion signal in each voxel
1381     %
1382     % dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel');
1383     % dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',coords);
1384     % dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',vxIndex);
1385     nBvecs  = feGet(fe,'nBvecs');
1386     nVoxels = feGet(fe,'n voxels');
1387     val     = reshape(feGet(fe,'dsigdemeaned'), nBvecs, nVoxels);
1388     val     = val(:,feGet(fe,'return voxel indices',varargin));
1389
1390   case {'dsigfullbyvoxel','dsigfullvox','voxdsigfull'}
1391     % Full (measured) signal in each voxel
1392     %
1393     % dSigByVoxel = feGet(fe,'dSig full by Voxel');
1394     % dSigByVoxel = feGet(fe,'dSig full by Voxel',coords);
1395     % dSigByVoxel = feGet(fe,'dSig full by Voxel',vxIndex);
1396     nBvecs  = feGet(fe,'nBvecs');
1397     nVoxels = feGet(fe,'n voxels');
1398     val     = reshape(feGet(fe,'dSig full'), nBvecs, nVoxels);
1399     val    = val(:,feGet(fe,'return voxel indices',varargin))';
1400
1401   case {'voxelrmse','voxrmse'}
1402     % A volume of RMSE values
1403     %
1404     % RMSE = feGet(fe,'vox rmse')
1405     % RMSE = feGet(fe,'vox rmse',coords)
1406     % RMSE = feGet(fe,'vox rmse',vxIndex)
1407     measured  = feGet(fe,'dsigdemeaned by voxel');
1408     predicted = feGet(fe,'pSig f vox');
1409     val       = sqrt(mean((measured - predicted).^2,1));
1410     val       = val(feGet(fe,'voxelsindices',varargin));
1411
1412   case {'voxelrmsevoxelwise','voxrmsevoxelwise'}
1413     % A volume of RMSE values optained with the voxel-wise (voxelwise) fit.
1414     %
1415     % RMSE = feGet(fe,'vox rmse voxelwise')
1416     % RMSE = feGet(fe,'vox rmse voxelwise',coords)
1417     % RMSE = feGet(fe,'vox rmse voxelwise',vxIndex)
1418     measured  = feGet(fe,'dsigdemeaned by voxel');
1419     predicted = feGet(fe,'pSig f voxel wise by voxel');
1420
1421     val       = sqrt(mean((measured - predicted).^2,1));
1422     val       = val(feGet(fe,'voxelsindices',varargin));
1423
1424   case {'voxelrmsetest','voxrmsetest'}
1425     % A volume of RMSE values with a subset of fibers' weights set to 0.
1426     %
1427     % RMSE = feGet(fe,'vox rmse',fiberIndices)
1428     % RMSE = feGet(fe,'vox rmse',fiberIndices,coords)
1429     % RMSE = feGet(fe,'vox rmse',fiberIndices,voxelIndex)
1430     measured  = feGet(fe,'dsigdemeaned by voxel');
1431     % Reshape the predicted signal by voxles
1432     predicted = reshape(feGet(fe,'pSig fiber test',varargin{1}), feGet(fe,'nBvecs'), feGet(fe,'nVoxels'));
1433     val       = sqrt(mean((measured - predicted).^2,1));
1434
1435     if length(varargin) == 2
1436       val       = val(feGet(fe,'voxelsindices',varargin));
1437     end
1438
1439   case {'residualsignalfibervoxel','resfibervox'}
1440     % Fibers' residual signal by voxel
1441     %
1442     % res = feGet(fe,'res sig fiber vox')
1443     % res = feGet(fe,'res sig fiber vox',coords)
1444     % res = feGet(fe,'res sig fiber vox',vxIndex)
1445     nBvecs  = feGet(fe,'nBvecs');
1446     nVoxels = feGet(fe,'n voxels');
1447     val     = reshape(feGet(fe,'res sig fiber'), nBvecs, nVoxels);
1448     val     = val(:,feGet(fe,'return voxel indices',varargin))';
1449
1450   case {'residualsignalfullvoxel','resfullvox'}
1451     % Full (measured) residual signal by voxel
1452     %
1453     % res = feGet(fe,'res sig full vox')
1454     % res = feGet(fe,'res sig full vox',coords)
1455     % res = feGet(fe,'res sig full vox',vxIndex)
1456     nBvecs  = feGet(fe,'nBvecs');
1457     nVoxels = feGet(fe,'n voxels');
1458     val     = reshape(feGet(fe,'res sig full'), nBvecs, nVoxels);
1459     val     = val(:,feGet(fe,'return voxel indices',varargin))';
1460
1461   case {'fiberressigwithmeanvoxel'}
1462     % Residual signal fiber model prediction - demeaned measured signal
1463     % with added mean signal. VOXEL FORM (nBvecs x nVoxel).
1464     %
1465     % This is used to reconstruct an image (volume) to be used for the
1466     % refinement process.
1467     %
1468     % res = feGet(fe,'fiber res sig with mean');
1469
1470     % predicted = feGet(fe,'psig fiber');
1471     % measured  = feGet(fe,'dsigdemeaned');
1472     % val = (measured     - predicted) + (measured_full - measured);
1473     val     = feGet(fe,'fiberressigwithmean');
1474     nBvecs  = feGet(fe,'nBvecs');
1475     nVoxels = feGet(fe,'n voxels');
1476     val     = reshape(val, nBvecs, nVoxels);
1477
1478     if ~isempty(varargin)
1479       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1480       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1481       % val              = val(voxelRowsToKeep,:);
1482       val = val(:, feGet(fe,'return voxel indices',varargin));
1483     end
1484
1485   case {'fiberressigwithmeanvox','resfibermeanvox'}
1486     % Fibers' residual signal by voxel with mean signal added (with added
1487     % isotropic component).
1488     %
1489     % This is used to compute the residual signal for the refinement.
1490     %
1491     % res = feGet(fe,'fiber res sig with mean vox')
1492     % res = feGet(fe,'fiber res sig with mean vox',coords)
1493     % res = feGet(fe,'fiber res sig with mean vox',vxIndex)
1494     nBvecs  = feGet(fe,'nBvecs');
1495     nVoxels = feGet(fe,'n voxels');
1496     val     = reshape(feGet(fe,'fiber res sig with mean'), nBvecs, nVoxels);
1497     val     = val(:,feGet(fe,'return voxel indices',varargin))';
1498
1499   case {'voxelsindices','returnvoxelindices','voxelindexes''returnvoxelindexes'}
1500     % Given an VOI or a set of indices to voxels returns the indices of the matching voxels inside the big
1501     % volume, which ordinarily represents the full connectome.
1502     %
1503     % voxelIndices = feGet(fe,'voxelsindices',coords)
1504     % voxelIndices = feGet(fe,'voxelsindices',voxelIndices)
1505     %                IMPORTANT: Indices MUST be a column vector for this
1506     %                code to work.
1507     %
1508     % coords is a Nx3 set of coordinates in image space
1509     % voxelIndices is a vector of 1's and 0's, there is a one for each
1510     % location the the connectome coordinates for which there is a match in
1511     % the coords
1512     %
1513     varargin = varargin{1};
1514     if (~isempty(varargin))
1515       if (size(varargin{1},2) == 3)
1516         % If a set of coordinates were passed in we return the indices.
1517         val = logical(feGet(fe,'find voxels',varargin{1}));
1518       else
1519         % If indices were passed in, we sort and return them.
1520         val = sort(varargin{1});
1521       end
1522     else
1523       % If no coordinates were passed at all, we return all the indices.
1524       val = true(feGet(fe,'n voxels'),1);
1525     end
1526
1527   case {'findvoxels','findvoxelindexes','findvoxelsinconnectome','findvoxelsinconnectomeroi', ...
1528       'voxel2index','coords2index'}
1529     % Given an VOI finds the indices of the matching voxels inside the big
1530     % volume, which ordinarily represents the full connectome.
1531     %
1532     % foundVoxels = feGet(fe,'find voxels',coords)
1533     %
1534     % coords is a Nx3 set of coordinates in image space
1535     % foundVoxels is a vector of 1's and 0's, there is a one for each
1536     % location the the connectome coordinates for which there is a match in
1537     % the coords
1538
1539     % Compute the values for a subset of voxels
1540     if isempty(varargin)
1541       % If no coordinates were passed at all, we return all the indices.
1542       val = ones(feGet(fe,'n voxels'),1);
1543     else
1544       % The stored coordinates are at a resolution of the image, typically
1545       % 2mm isotropic.  The VOI should also be in image resolution.
1546       % ---- Franco:
1547       % This is how I had it. I think it is worng:
1548       % val = ismember(feGet(fe,'roi coords'), varargin{1}, 'rows'); % This is slow
1549       % This is hwo I think it should be:
1550       [~,val] = ismember(varargin{1}, feGet(fe,'roi coords'),'rows'); % This is slow
1551     end
1552
1553   case {'voxelcoords2voxelrows','coords2rows'}
1554     % Given a set of VOI coords finds the row numbers of the Model matrix
1555     % (or equivalently the dSig vector) that represent the data for this
1556     % set of VOI coords.
1557     %
1558     % foundVoxels = feGet(fe,'coords 2 rows',coords)
1559     %
1560     % coords      - a Nx3 set of coordinates in image space
1561     % foundVoxels - a binary vector that is 1 for each Model matrix row
1562     %               that corresponds to at least one of the coords.
1563     val = feGet(fe,'voxel rows',find(feGet(fe,'find voxels',varargin{1})));
1564
1565     % ------ Spatial coordinate transforms for voxels and fg to coordinate frames
1566   case {'xformimg2acpc','xform2acpc','img2acpc','img2acpcxform'}
1567     % Quaternian transformation from IMAGE space to ACPC space.
1568     %
1569     % xform = feGet(fe,'xform')
1570     val = fe.life.xform.img2acpc;
1571   case {'xformacpc2img','xform2img','acpc2img','acpc2imgxform'}
1572     % Quaternian transformation from ACPC space to IMAGE space.
1573     %
1574     % xform = feGet(fe,'xform')
1575     val = fe.life.xform.acpc2img;
1576   case {'volumesize','dims','dim','imagedim'}
1577     % Dimensions of the DW volume.
1578     %
1579     % dim = feGet(fe,'dims')
1580     val = fe.life.imagedim;
1581   case {'mapsize'}
1582     % Dimensions of the maps of parameters and results.
1583     %
1584     % dims = feGet(fe, 'mapsize')
1585     val = fe.life.imagedim(1:3);
1586
1587   case {'anatomyfile'}
1588     % Path to the 3D Anatomy Volume.
1589     % anatomyfile = feGet(fe, 'anatomy file')
1590     val = fe.path.anatomy;
1591   case 'dtfile'
1592     % Diffusion weighted file used for testing results
1593     % dtfile = feGet(fe,'dtfile')
1594      val = fe.path.dtfile;
1595
1596   otherwise
1597     help('feGet')
1598     fprintf('[feGet] Unknown parameter << %s >>...\n',param);
1599     keyboard
1600 end
1601
1602 end % END MAIN FUNCTION